public class Tree{
    private String name;
    private String location;
    private int age;

    public Tree (String name,string location,int age);
        this.name=name;
        this.location=location;
        this.age=age;

    public string getname();
        return name;

    public string getlocation();
        return location;

    public int getage();
        return age;

    public toString()
        return system.out.println
}